language: minimal
os:
  - linux
dist: bionic
branches:
  except:
    - master
env:
  - IMAGE_NAME=$REGISTRY_USER/k8s-cli
services:
  - docker

stages:
  - name: Build
  - name: Test
  - name: Deploy
  - name: Deploy latest
  - name: Cleanup

jobs:
  include:
    - stage: Build
      script:
        - docker build -t $IMAGE_NAME .
        - git_sha="$(git rev-parse --short HEAD)"
        - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"        
        - docker tag $IMAGE_NAME $IMAGE_NAME:$TRAVIS_COMMIT
        - docker push $IMAGE_NAME:$TRAVIS_COMMIT
    - stage: Test
      script:
        - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
        - docker run $IMAGE_NAME:$TRAVIS_COMMIT version --client
    - stage: Deploy
      script:
        - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
        - docker pull $IMAGE_NAME:$TRAVIS_COMMIT
        - docker tag $IMAGE_NAME $IMAGE_NAME:$TRAVIS_BRANCH        
        - docker push $IMAGE_NAME:$TRAVIS_BRANCH
    - stage: Deploy latest
      if: $TRAVIS_BRANCH = $VERSION
      script:
        - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
        - docker pull $IMAGE_NAME:$TRAVIS_BRANCH
        - docker tag $IMAGE_NAME $IMAGE_NAME:latest
        - docker push $IMAGE_NAME:latest
    - stage: Cleanup
      script:
        - curl -u $REGISTRY_USER:$REGISTRY_PASS -X 'DELETE' https://cloud.docker.com/v2/repositories/"$REGISTRY_USER"/"$IMAGE_NAME"/tags/"$TRAVIS_COMMIT"/