language: minimal
os:
  - linux
dist: bionic
services:
  - docker
env:
  - VERSION=v1.15.3

stages:
  - name: Build
  - name: Push
  - name: Push latest

jobs:
  include:
    - stage: Build
      script:
        - docker build -t $IMAGE_NAME .
        - docker run $IMAGE_NAME:$TRAVIS_COMMIT version --client
    - stage: Push
      if: branch != master
      script:
        - docker build -t $IMAGE_NAME:$TRAVIS_BRANCH .
        - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
        - docker push $IMAGE_NAME:$TRAVIS_BRANCH
    - stage: Push latest
      if: branch = master
      script:
        - docker build -t $IMAGE_NAME:$TRAVIS_BRANCH
        - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
        - docker tag $IMAGE_NAME:$TRAVIS_BRANCH $IMAGE_NAME:latest
        - docker push $IMAGE_NAME:latest

notifications:
  slack:
    secure: "RMUC1W5tIMmVlZb09oKLauLkDrcPEojqMcRk0syqSV/iCGYZNg8APm5WhdtMI0xe4P/YaaQG1ueTK3lbLji0HOX8O4wL+Oj+lbpQ4KyWAMd0gsuJj0KIlPZHde2uVD/h11nFeVgJVbt7Rhl1jpLz3Wq8ic50Y9M+7txxwp7/2uGg3WClOrf4iyz6VX8nx9AatPquero0zFWWUnQB/QKk2uzvFrXjGSMAo+rUNxKaQnEqeAB+pMAWPDJhxnFsiWWEQo0p43jzT2WwfuUhFLEMa8pq2CNujposJzaamf485KL7ev8Lac9Klpuxe0R6uG6vpBJl0YCwzDI0xHkwt8LImh/jWybEu6I1glx5K9EDdjhJzojieFcn4jxIPynipJIIfmBv+FMuoxv5bN+EIg0khcPicfOSso5+EDb1nNzM3jtH+PjjWxbGslChpOwMR8Ssqy8ha8gf4vLEF3IiEP9jczM1NUD4ZdgJaiFBUL0wiRxBo+wC/U88qqtHW4BX8WEsykNpCvoDUnS465TMAVe1YhoTVeDWA70hHxnm2sJIGr0fD0Tj4kI2/6gKTcyK4F9gn93qDNGZ7JdQFhZqfjmMReZotr0GQ2bc8ZKVJizJ9erRgg37osVpN0+0lt1vXdDTDduvDgE2IzOcKETHJZh6KBID2akSSQFTE36vIVyLEEY="